#!/usr/bin/env bash

# EDIT THESE BEFORE RUNNING

# Variables for the backup script
## Location of backup SOURCE
addr_src="/home"

## Location of backup DESTINATION
addr_dest="rsync://192.168.0.253/sad-machine/"

## List of patterns to exclude from backup
### Make sure this file exists, then add anything you want to it (or leave it empty)
excludelist=$HOME/.config/backup/excludelist

# Variables for the menu script
## Path to the main backup script. This is so it knows what to run.
backup_script=$HOME/scripts/backup

## dmenu-like program (rofi in my case)
dmenu_prompt="rofi -dmenu -p backupctl -lines 2"

## Terminal command for showing the log
terminal_command="kitty bash -c"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# You probably don't need to change these

## Location of log file
logfile=$HOME/.log/backup.log

## Location of PID (process ID) file
pidfile=/tmp/backup.pid
