#!/usr/bin/env bash

icon=""
icon_progress=" %{F#50aefa}%{F-}"
icon_never=" %{F#f0ab77}%{F-}"
icon_failed=" %{F#fb7c9a}%{F-}"
icon_outdated=" %{F#dc89d5}%{F-}"
icon_finished=" %{F#5ad876}%{F-}"

source $HOME/.config/backup/config

while [ true ]; do
	if [ -e $pidfile ] && kill -0 2&>1 > /dev/null `cat $pidfile`; then
		icon="$icon_progress"
	elif [[ ! -e $logfile ]]; then
		icon="$icon_never"
	elif [[ $(tail -n 1 $logfile) =~ ^rsync\ error: ]]; then
		icon="$icon_failed"
	else
		age=$(( $(date +%s) - $(date -r $logfile +%s) ))
		# older than 1 week
		if [[ $age -gt 604800 ]]; then
			icon="$icon_outdated"
	# newer than 24 hours
	elif [[ $age -lt 86400 ]]; then
			icon="$icon_finished"
		fi
	fi

	echo "$icon"
	sleep 10
done
