#!/usr/bin/env bash

next () {
	if [ $MONTH -ge 12 ]; then
		MONTH=1
		YEAR=$(expr $YEAR + 1)
	else
		MONTH=$(expr $MONTH + 1)
	fi
}

prev () {
	if [ $MONTH -le 1 ]; then
		MONTH=12
		YEAR=$(expr $YEAR - 1)
	else
		MONTH=$(expr $MONTH - 1)
	fi
}

MONTH=$(date -u +"%m")
YEAR=$(date -u +"%Y")

while : ; do
	clear
	cal $MONTH $YEAR
	read -n 1 -p ":" key
	case $key in
		[ | , ) prev ;;
		] | . ) next ;;
		* ) exit 0 ;;
	esac
done
