#!/usr/bin/env bash

disconnected=""
wireless_connected=""
ethernet_connected=""

results=()
ifaces="$(ip link | awk '/state UP/ {print $2}')"

if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com) &>/dev/null; then
    if grep -q "^e" <<< "$ifaces"; then
        results+=("$ethernet_connected")
    fi
	if grep -q "^w" <<< "$ifaces"; then
        results+=("$wireless_connected")
    fi
else
    results+=("$disconnected")
fi


out=$(printf "\040\040\040\040%s" "${results[@]}")
# for i in ${!results[@]}; do
# 	if [ $i > 0 ]; then
# 		out="$out\040\040\040\040"
# 	fi
# 	out="$out${results[i]}"
# done

echo -e ${out:4}
