#!/usr/bin/env python3

import time
from pyphoon.lib.astro import phase, unix_to_julian

def moon_icon():
	icon_count = 27
	icon_start = 0xe38d

	moon_phase, _, _, _, _, _, _ = phase(unix_to_julian(time.time()))
	return chr(int(moon_phase * icon_count) + icon_start)

if __name__ == "__main__":
	print(moon_icon())
