#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
ssid=$(nmcli c | grep wlp3s0 | awk '{print ($0)}')

if [ $status ] ; then
	icon="睊"
	text=""
	class=""
else
	icon="直"
	text="${ssid}"
	class="good"
fi

if [[ "$1" == "--CLASS" ]]; then
	echo $class
elif [[ "$1" == "--SSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi
