#!/bin/env bash

# control my backup script with rofi

source $HOME/.config/backup/config

# is a backup currently running?
if [ -e $pidfile ] && kill -0 &>1 > /dev/null `cat $pidfile`; then
	options=$'cancel current backup\nwatch log'
else
	options=$'back up now\nread log'
fi

choice=$(echo "$options" | $dmenu_prompt)

case $choice in
	"back up now")
		$backup_script &
	;;
	"cancel current backup")
		$backup_script cancel
	;;
	"watch log")
		$terminal_command "watch -n 5 tac \"$(echo $logfile)\""
	;;
	"read log")
		$terminal_command "tac \"$(echo $logfile)\" | less"
	;;
esac
