#!/bin/env bash

# control my backup script with rofi

source $HOME/.config/backup/config

rofi_prompt="rofi -dmenu -p backupctl -lines 2"

# is a backup currently running?
if [ -e $pidfile ] && kill -0 &>1 > /dev/null `cat $pidfile`; then
	options=$'cancel current backup\nwatch log'
else
	options=$'back up now\nread log'
fi

choice=$(echo "$options" | $rofi_prompt)

case $choice in
	"back up now")
		$backup_script &
	;;
	"cancel current backup")
		$backup_script cancel
	;;
	"watch log")
		$TERMINAL bash -c "watch -n 5 tac \"$(echo $logfile)\""
	;;
	"read log")
		echo $logfile
		$TERMINAL bash -c "tac \"$(echo $logfile)\""
	;;
esac
