#!/bin/env bash

# Display layout menu

mode_single () {
	xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off
}
mode_dual () {
	xrandr --output eDP-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --off
}

rofi_command="rofi -lines 2"
options=$'single\ndual'

eval mode_$(echo "$options" | $rofi_command -dmenu -p 'layout')

$HOME/scripts/polybar
