#!/usr/bin/env bash

# Display layout menu

mode_single () {
	xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
	cleanup
}
mode_dual () {
	xrandr --output eDP-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal
	cleanup
}
mode_triple () {
	xrandr --output HDMI-0 --mode 1680x1050 --pos 3520x0 --rotate normal --output DP-0 --primary --mode 1600x900 --pos 1920x150 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 0x150 --rotate normal
	cleanup
}

cleanup () {
	feh $(cat $HOME/.cache/wal/wal)
	$HOME/scripts/polybar
}

options=$'single\ndual\ntriple'
eval mode_$(echo "$options" | rofi -dmenu -p 'display layout' -lines 3)
