#!/usr/bin/env bash

# rofi menu that mimicks GnuPG pinentry[1], designed specifically for rbw[2]. it may not work with other pinentry-dependent programs.
# [1] https://www.gnupg.org/related_software/pinentry/index.html
# [2] https://github.com/doy/rbw

prompt=$(cat | grep SETPROMPT | cut -f 2- -d ' ')
pass=$(rofi -dmenu \
	-password \
	-no-fixed-num-lines \
	-p "$prompt")

if [ -z $pass ]; then
	echo -e "OK Pleased to meet you\nOK\nOK\nOK\nERR 83886179 Operation cancelled <Pinentry>"
else
	echo -e "OK Pleased to meet you\nOK\nOK\nOK\nD ${pass}\nOK"
fi
