#!/bin/bash

# make tweets using rofi

tweet_text=$(rofi -dmenu -p 'tweet' -lines 0 -width 1000)
if [[ -z "$tweet_text" ]]; then
	#notify-send "tweet.sh" "Tweet empty"
	exit 1
fi

output=$(tweet.sh post "$tweet_text")

if [[ 'null' == $(echo '$output' | jq -r '.id') ]]; then
	notify-send "tweet.sh" "$(echo '$output' | jq -r '.errors[0].message')"
else
	notify-send "tweet.sh" "Tweet sent!"
fi
