#!/usr/bin/env bash

# Source: https://github.com/luyves/polybar-rofi-usb-mount
# Slightly modified by me

rofi_cmd='rofi -dmenu -i -lines 3'
notif_cmd(){
	notify-send -i media-removable "Removable media manager" "$@"
}
usb_re='sd[b-z]'

usbcheck(){
	mounteddrives="$(lsblk -rpo "name,type,size,mountpoint" | grep $usb_re | awk '$2=="part"&&$4!=""{printf "%s (%s)\t  ",$1,$3}')"
	if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
		echo "  #  $mounteddrives"
	else
		if [ $(echo "$usbdrives" | wc -w) -gt 0 ]; then
			echo "  #  "
		else
			echo ""
		fi
	fi
}

mountusb(){
	chosen=$(echo "$usbdrives" | $rofi_cmd -p "mount" | awk '{print $1}')
	mountpoint=$(udisksctl mount --no-user-interaction -b "$chosen" 2>/dev/null) && notif_cmd "$chosen mounted to $mountpoint"

}

umountusb(){
	chosen=$(echo "$mounteddrives" | $rofi_cmd -p "unmount" | awk '{print $1}')
	mountpoint=$(udisksctl unmount --no-user-interaction -b "$chosen" 2>/dev/null) && notif_cmd "$chosen unmounted"
	udisksctl power-off --no-user-interaction -b "$chosen"
}

umountall(){
	for chosen in $(echo $(lsblk -rpo "name,type,size,mountpoint" | grep $usb_re | awk '$2=="part"&&$4!=""{printf "%s\n",$1}')); do
		udisksctl unmount --no-user-interaction -b "$chosen"
		udisksctl power-off --no-user-interaction -b "$chosen"
	done
	notif_cmd "Unmounted all USB drives."
}


usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep $usb_re | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
mounteddrives="$(lsblk -rpo "name,type,size,mountpoint" | grep $usb_re | awk '$2=="part"&&$4!=""{printf "%s (%s)\n",$1,$3}')"

case "$1" in
	--check)
		usbcheck
		;;
	--mount)
		if [ $(echo "$usbdrives" | wc -w) -gt 0 ]; then
			mountusb
		else
			notif_cmd "No USB drive(s) detected." && exit
		fi
		;;
	--umount)
		if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
			umountusb
		else
			notif_cmd "No USB drive(s) to unmount." && exit
		fi
		;;
	--umount-all)
		if [ $(echo "$mounteddrives" | wc -w) -gt 0 ]; then
			umountall
		else
			notif_cmd "No USB drive(s) to unmount." && exit
		fi
		;;
	*)
		mode="$(echo $'Mount...\nUnmount...\nUnmount all' | $rofi_cmd -p "USB menu")"
		case "$mode" in
			"Mount...") $0 --mount ;;
			"Unmount...") $0 --umount ;;
			"Unmount all") $0 --umount-all ;;
		esac
		;;
esac
