#!/usr/bin/env python3

# Get dictionary definitions from Wiktionary using Rofi
# (c) 2020 katacarbix
# Free to use and modify.

import json
import sys
from subprocess import Popen, PIPE
from wiktionaryparser import WiktionaryParser

py_cmd = sys.argv[0]

POStable = {
	'adjective':	'(adj) ',
	'adverb':		'(adv) ',
	'article':		'(art) ',
	'conjunction':	'(con) ',
	'interjection':	'(int) ',
	'letter':		'(l) ',
	'noun':			'(n) ',
	'numeral':		'(num) ',
	'preposition':	'(pre) ',
	'pronoun':		'(p) ',
	'proper noun':	'(n p) ',
	'verb':			'(v) '
}

parser = WiktionaryParser()
parser.set_default_language('english') # Change this to the language you want to use.

def open_rofi(entries, prompt='define'):
	rofi = Popen(
		[
			'rofi',
			'-dmenu',
			'-p', prompt,
			'-width', '1000',
			'-no-show-icons'
		],
		stdin=PIPE,
		stdout=PIPE
	)
	(stdout, _) = rofi.communicate(input=entries.encode('UTF-8'))
	return rofi.returncode, stdout

def copy(text):
	text = text.decode('UTF-8').strip().split(' ', 1)[1]
	Popen(args=['xsel', '-i', '-b'], stdin=PIPE) \
		.communicate(input=text.encode('utf-8'))

def lookup(query):
	query = query.decode('UTF-8').strip()
	word = parser.fetch(query)
	entries = []
	
	for defn in word[0]['definitions']:
		for text in defn['text']:
			if text[:len(query)] != query:
				entries.append(POStable[defn['partOfSpeech']] + text.rstrip(':'))
	
	(_, query) = open_rofi("\n".join(entries))
	if len(query) > 0:
		if query.decode('UTF-8')[0] != '(':
			lookup(query)
		else:
			copy(query)
	else:
		return

if __name__ == '__main__':
	if len(sys.argv) == 1:
		(_, query) = open_rofi('Type a word and press Enter.')
		if len(query) > 0:
			lookup(query)
	elif len(sys.argv) > 1:
		lookup(' '.join(sys.argv[1:]))
