#! /bin/bash

# Based on this script: https://bbs.archlinux.org/viewtopic.php?pid=1037160#p1037160

SLEEP_TIME=5   # Default time between checks.
SAFE_PERCENT=20  # Still safe at this level.
DANGER_PERCENT=10  # Warn when battery at this level.
CRITICAL_PERCENT=2  # Shut down when battery at this level.

function notifyBattery
{
	notify-send -u critical "Battery level low!" "Please plug me in\!"
}


while [ true ]; do

	rem_bat=$(acpi -b | grep -Eo "[0-9]+%" | grep -Eo "[0-9]+")

	if [[ -n $(acpi -b | grep -i discharging) ]]; then
		if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
			SLEEP_TIME=10
		else
			SLEEP_TIME=1
			if [[ $rem_bat -le $DANGER_PERCENT ]]; then
				notifyBattery
			fi
			if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
				sudo poweroff
			fi
		fi
	else
		if [[ $rem_bat -lt $SAFE_PERCENT ]]; then
			killall dunst; dunst &
			SLEEP_TIME=5
		else
			SLEEP_TIME=20
		fi
	fi

	sleep ${SLEEP_TIME}m

done
