#!/usr/bin/env bash

# Source: https://bbs.archlinux.org/viewtopic.php?pid=1037160#p1037160

SLEEP_TIME=5   # Default time between checks.
SAFE_PERCENT=30  # Still safe at this level.
DANGER_PERCENT=10  # Warn when battery at this level.
CRITICAL_PERCENT=2  # Shut down when battery at this level.

notifID=296 # Random ID for dunstify

notify_battery () {
	dunstify -u critical "Battery level low!" "Please plug me in!" -r $notifID
}

while [ true ]; do
	rem_bat=$(acpi -b | grep -v "Battery [0-9].*unavailable" | sed -re "s/.*\b([0-9]+)%.*/\1/")
	echo $rem_bat

	if [[ -n "$(acpi -b | grep -v "Battery [0-9].*unavailable" | grep -i discharging)" ]]; then
		if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
			SLEEP_TIME=10
		else
			SLEEP_TIME=1
			if [[ $rem_bat -le $DANGER_PERCENT ]]; then
				notify_battery
			fi
			if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
				# sudo pm-hibernate
				echo "hibernate!"
			fi
		fi
	else
		dunstify -C $notifID
		if [[ $rem_bat -lt $SAFE_PERCENT ]]; then
			SLEEP_TIME=5
		else
			SLEEP_TIME=10
		fi
	fi

	sleep ${SLEEP_TIME}m

done
