#!/usr/bin/env python3

# Tool for displaying terminal colors.
# (c) 2020 - katacarbix
# Free to use and modify.

import sys
import random

patterns = {
	'swatches': [
		'',
		'    tttttt ',
		'    tttttt ',
		' bbbtttttt ',
		' bbbbbb    ',
		' bbbbbb    ',
		''
	],
	'swatches2': [
		'',
		' tttttt    ',
		' tttttt    ',
		' tttbbbbbb ',
		'    bbbbbb ',
		'    bbbbbb ',
		''
	],
	'squares': [
		'',
		'tttttttttt',
		'ttbbbbbbtt',
		'ttbbbbbbtt',
		'ttbbbbbbtt',
		'tttttttttt',
		''
	],
	'mini': [
		'',
		'  tttt',
		''
	],
	'invaders': [
		'',
		'    tt          tt      ',
		'      tt      tt        ',
		'    tttttttttttttt      ',
		'  tttt  tttttt  tttt    ',
		'tttttttttttttttttttttt  ',
		'tt  tttttttttttttt  tt  ',
		'tt  tt          tt  tt  ',
		'      tttt  tttt        ',
		'',
		'    bb          bb      ',
		'      bb      bb        ',
		'    bbbbbbbbbbbbbb      ',
		'  bbbb  bbbbbb  bbbb    ',
		'bbbbbbbbbbbbbbbbbbbbbb  ',
		'bb  bbbbbbbbbbbbbb  bb  ',
		'bb  bb          bb  bb  ',
		'      bbbb  bbbb        '
		''
	],
	'creepers': [
		'',
		'  tttt    tttt  ',
		'  tttt    tttt  ',
		'      tttt      ',
		'    tttttttt    ',
		'    tttttttt    ',
		'    tt    tt    ',
		''
	]
}
block = "\u2588" # block char code
reset = "\033[0m" # reset color sequence

def color(c): # color escape sequence
	return "\033[" + str(30+c) + "m"

def draw(key):
	for line in patterns[key]:
		for top in range(8):
			bottom = top + 60
			
			for char in line:
				if char == ' ':
					print(char, end='')
				elif char == 't':
					print(color(top) + block, end='')
				elif char == 'b':
					print(color(bottom) + block, end='')
				else:
					print(color(top) + char, end='')
		print(reset)

if __name__ == "__main__":
	if len(sys.argv) < 2:
		draw(random.choice(list(patterns.keys())))
	else:
		try:
			draw(str(sys.argv[1]))
		except KeyError:
			print("Unknown pattern: '" + str(sys.argv[1]) + "'")
