#!/usr/bin/env sh

if [ $(whoami) != reese ]; then
	sudo -u reese "$0" "$@"
	exit
fi

log=~/.log/davsync.log

echo "[$(date '+%F %H:%M:%S')]" >> $log
/usr/bin/vdirsyncer discover >> $log 2>&1 && \
/usr/bin/vdirsyncer sync >> $log 2>&1 && \
$HOME/.local/bin/khal printcalendars >> $log
echo "" >> $log
