#!/usr/bin/env bash

# disk imager with progress bar
# by katacarbix
# do whatever you want

bs="4M"
pv_opts="-B $bs -e -r -p -b"


# Elevate script
if (($EUID != 0)); then
	if [ -t 0 ]; then
		sudo -H "$0" "$@"
	else
		sudo -AH "$0" "$@"
	fi
	exit
fi

# Notification wrapper
notify () {
	if [ -t 0 ]; then
		echo $@
	else
		sudo -u reese dunstify $@
	fi
}

# The actual logic
pv $pv_opts $1 > $2
if [ $? -eq 0 ]; then
	notify "data transferred"
else
	notify "uh oh, something went wrong" "exit code: $?"
fi
