#!/usr/bin/env fish

# TODO: implement a persistent history method that works
# set -x fish_history "gcalcli"

set -l cmd "gcalcli"
set -l arg "calm"

while true # TODO: catch ^C
	eval $cmd $arg

	set cmd "gcalcli"
	set arg ""
	read -p "set_color brwhite -b brblue; echo -n '  '; set_color brblue -b normal; echo -n ' '; set_color normal" -l --list opts
	switch $opts[1]
		case 'l' 'ls'
			set arg "list"
		case 's' '/'
			set arg "search $opts[2..-1]"
		case 'd' 'rm'
			set arg "delete $opts[2..-1]"
		case 'w' 'week'
			set arg "calw $opts[2..-1]"
		case 'm' 'month'
			set arg "calm $opts[2..-1]"
		case 'h' 'help' '\?'
			set arg "$opts[2] -h"
		case 'v' 'version'
			set arg "--version"
		case 'q' 'quit'
			set cmd "break"
			set arg ""
		case ''
			set cmd ""
			set arg ""
		case '*'
			set arg "$opts"
	end
end
