#!/usr/bin/env bash

# Create a popup terminal window with kitty and i3
# USAGE: kitty-popup [width] [height] [command]

kitty -o allow_remote_control=yes --listen-on unix:/tmp/kitty-popup bash &
sleep 0.2s
kitty @ --to unix:/tmp/kitty-popup send-text "i3-msg floating enable\ni3-msg resize set $1 px $2 px\ni3-msg move position center\n"
shift; shift
kitty @ --to unix:/tmp/kitty-popup send-text "clear\n$@\n"
