#!/usr/bin/env node

const fs = require('fs');
const cson = require('cson');
const { spawn } = require('child_process');

const colors = require('/home/reese/.cache/wal/colors.json');

// Update atom's configuration
let toggle_atom = mode => {
	let themes = {
		'dark': ["fang-ui", "eupho-syntax"],
		'light': ["wave-ui", "one-light-syntax"]
	}
	
	let filename = "/home/reese/.atom/config.cson";
	let conf = cson.load(filename);
	conf['*'].core.themes = themes[mode];
	fs.writeFileSync(filename, cson.stringify(conf));
	console.log('modified atom config.');
}

let toggle_fish = mode => {
	let fish_variables = '/home/reese/.config/fish/fish_variables';
	const mklink = spawn('ln', ['-sf', `${fish_variables}_${mode}`, `${fish_variables}`]);
	mklink.on('close', code => {
		if (code == 0) console.log(`linked fish variables.`);
		else console.error(`an error occurred when linking fish variables. (exit code ${code})`);
	});
}

(() => {
	let mode;
	if (process.argv.length > 2 && process.argv[2] == '-l'){
		mode = 'light';
	} else {
		mode = 'dark';
	}

	toggle_atom(mode);
	toggle_fish(mode);
})()

module.exports.atom = toggle_atom;
module.exports.fish = toggle_fish;
