#!/usr/bin/env bash

source ~/.cache/wal/colors.sh
i3lock_bg="/tmp/i3lock_bg.png"

i3lock \
	--image $i3lock_bg \
	--fill \
\
	--pointer=default \
	--indicator \
\
	--pass-media-keys \
	--pass-screen-keys \
	--pass-power-keys \
\
	--verif-color="${foreground/'#'}ff" \
	--wrong-color="${color1/'#'}ff" \
\
	--inside-color="00000000" \
	--insidever-color="00000000" \
	--insidewrong-color="00000000" \
\
	--ring-color="${foreground/'#'}ff" \
	--ringver-color="${color2/'#'}ff" \
	--ringwrong-color="${color3/'#'}ff" \
\
	--keyhl-color="${color2/'#'}ff" \
	--bshl-color="${color5/'#'}ff" \
\
	--separator-color="${foreground/'#'}ff" \
	--line-uses-inside \
\
	--ring-width=18 \
	--ignore-empty-password \
	# --no-verify
