#!/bin/bash

source ~/.cache/wal/colors.sh

i3lock \
	--color="00000066" \
	--indicator \
\
	--pass-media-keys \
	--pass-screen-keys \
	--pass-power-keys \
\
	--verifcolor="${foreground/'#'}ff" \
	--wrongcolor="${color1/'#'}ff" \
\
	--insidecolor="00000000" \
	--insidevercolor="00000000" \
	--insidewrongcolor="00000000" \
\
	--ringcolor="${foreground/'#'}ff" \
	--ringvercolor="${color2/'#'}ff" \
	--ringwrongcolor="${color3/'#'}ff" \
\
	--keyhlcolor="${color2/'#'}ff" \
	--bshlcolor="${color5/'#'}ff" \
\
	--separatorcolor="${foreground/'#'}ff" \
	--line-uses-inside \
\
	--ring-width=18 \
#	--no-verify \
