#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# wait
while pgrep -u $USER -x polybar >/dev/null; do sleep 1; done

# Launch main bar
polybar -q -c ~/.config/polybar/config.ini main &
