#!/usr/bin/env bash

# Terminate already running bar instances
killall -q polybar

# wait
sleep 2

source ~/.cache/wal/colors.sh
# export envar with alpha set.
export bgtrans="#cc${color0/'#'}"

# Launch main bar
polybar -q -c ~/.config/polybar/config.ini main &
