#!/bin/bash

wppath=${1:-~/Pictures/Wallpapers/favorites/}
wal --backend colorz -i "$wppath"

sleep 1

# update firefox theme
#pywalfox update

# update vivaldi theme (silent)
~/scripts/vivwal >/dev/null &

# update atom theme
touch ~/.atom/styles.less

# compile discord theme
sassc ~/git/github.com/katacarbix/discord-stuff/themes/bliss/pywal.scss ~/git/github.com/katacarbix/discord-stuff/themes/bliss/pywal.css

# compile android messages theme
# sassc ~/.config/android-messages/css/user-style.scss ~/.config/android-messages/css/user-style.css

# rgb lights (keyboard, lightbulbs, etc.)
python3 ~/scripts/rgbctl
