#!/bin/env python3

# Sets the keyboard of my Razer Blade 15 to a vivid color

import sys, json
from colour import Color
import openrazer.client

with open('/home/reese/.cache/wal/colors.json', 'r') as f:
	obj = json.loads(f.read())
	
	c = Color(obj['colors']['color'+sys.argv[1]])
	c.saturation = 1
	c.luminance = 0.65
	
	rgb = [int(x*255) for x in c.rgb]

	openrazer.client.DeviceManager().devices[0].fx.static(*rgb)
