#!/bin/bash

#i3-msg "workspace 2; append_layout ~/.config/i3/layouts/2.json"
i3-msg "workspace 3; append_layout ~/.config/i3/layouts/3.json"
i3-msg "workspace 4; append_layout ~/.config/i3/layouts/4.json"
i3-msg "workspace 5; append_layout ~/.config/i3/layouts/5.json"

sleep 1

# atom &
# vivaldi --remote-debugging-port=9222 &
firefox &
discord &
caprine &
gtk-launch android-messages &
