#!/usr/bin/env bash

i3-msg "workspace 2; append_layout ~/.config/i3/layouts/2.json"
i3-msg "workspace 3; append_layout ~/.config/i3/layouts/3.json"
i3-msg "workspace 4; append_layout ~/.config/i3/layouts/4.json"
i3-msg "workspace 5; append_layout ~/.config/i3/layouts/5.json"
i3-msg "workspace 10; append_layout ~/.config/i3/layouts/10.json"

sleep 1

gtk-launch sublime_text
gtk-launch firefox
gtk-launch discord-canary
gtk-launch caprine
gtk-launch thunderbird
