#!/bin/bash

# Battery warning script
~/scripts/battery-notify &

# Start compositor
compton -b

# Disable screensaver
xset -dpms s off
# ...and use xautolock instead
xautolock -time 20 -locker "~/scripts/lock" &

# Set wallpaper and colors
~/scripts/pywal &

# Applications
redshift &
nm-applet &
blueman-tray &
