#!/usr/bin/env bash

# Start compositor
compton -b

# Disable screensaver
xset -dpms s off
# ...and use xidlehook instead
xidlehook --not-when-fullscreen --timer 1200 "$HOME/scripts/lock" "" &

# Enable touchpad gestures
libinput-gestures-setup start

# Set wallpaper and colors
~/scripts/pywal -a

# Battery warning script
~/scripts/battery-notify &

# Clipboard manager
clipster -d &

# Applications
dunst &
redshift &
nm-applet &
blueman-tray &
