#!/usr/bin/env bash

# Elevate script
if (($EUID != 0)); then
	if [ -t 0 ]; then
		sudo -H "$0" "$@"
	else
		sudo -AH "$0" "$@"
	fi
	exit
fi


# Notification wrapper to de-escalate command
notify_update () {
	[ -t 0 ] && echo $1
	sudo -u reese notify-send -i software-update-available-symbolic "$1"
}


update_apt () {
	apt-get update
	apt-get upgrade -y
	apt-get autoremove -y
	apt-get install -f
}

update_npm () {
	npm update -g
	npm install -g electron --unsafe-perm=true # electron is stupid
	npm install -g npm
}

update_pip () {
	pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip3 install -U
	sudo -Hu reese pip3 list --outdated --user --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 sudo -Hu reese pip3 install -U --user
}

update_omf () {
	sudo -u reese fish -c "omf update"
}

update_cargo () {
	sudo -u reese rustup update
	sudo -i -u reese bash -c "cargo install --list | grep -o '^[^ ]*' | xargs -n1 cargo install"
}


# Parse arguments
do_update_apt=false
do_update_npm=false
do_update_pip=false
do_update_omf=false
do_update_cargo=false

if [ $# -eq 0 ]; then
	do_update_apt=true
	do_update_npm=true
	do_update_pip=true
	do_update_omf=true
	do_update_cargo=true
else
	while(($#)); do
		case "$1" in
			apt)
				do_update_apt=true
				shift
				;;
			npm)
				do_update_npm=true
				shift
				;;
			pip)
				do_update_pip=true
				shift
				;;
			omf)
				do_update_omf=true
				shift
				;;
			cargo)
				do_update_cargo=true
				shift
				;;
		esac
	done
fi

notify_update "Fetching updates..."

$do_update_apt && update_apt >/dev/null 2>&1 &
$do_update_npm && update_npm>/dev/null 2>&1 &
$do_update_pip && update_pip>/dev/null 2>&1 &
$do_update_omf && update_omf>/dev/null 2>&1 &
$do_update_cargo && update_cargo>/dev/null 2>&1 &

wait
notify_update "Updates complete."
