#!/bin/bash

# Elevate script
if (($EUID != 0)); then
	SUDO_ASKPASS=$(which askpass-rofi) sudo -AH "$0" "$@"
	exit
fi


# Notification wrapper to de-escalate command
notify_update () {
	sudo -u reese notify-send -i software-update-available-symbolic "$1"
}


update_apt () {
	apt update
	apt upgrade -y
	apt autoremove -y
	apt install -f
}

update_npm () {
	npm update -g
	npm install -g electron --unsafe-perm=true # electron is stupid
}

update_pip () {
	pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U --use-feature=2020-resolver
}


notify_update "Starting updates..."

update_apt &
update_npm &
update_pip &

wait
notify_update "Updates complete."
